### PR TITLE
[PR]: Updated Key Messages

### PR DESCRIPTION
**Pull request by britsanto**
- Updated the Key Messages in Overview

### CODE REVIEW

**Comment by amichuda** [comment]
This looks good, but so you dont want to change the folder names from `tools -> minimod_tools` ?

**Comment by britsanto** [comment]
I see that the folder name has already changed to minimod_tools. Is this what you mean?
Screen Shot 2021-06-09 at 1 00 21 PM

**Comment by amichuda** [comment]
Yes, because it was part of one of the previous pull requests. Do you want
to reverse that? If not, then I suggest charging the yaml file to reflect
the new folder names.

**Comment by britsanto** [comment]
OH! I'm so sorry my brain is not working properly today, I think I finally understand your point.
So because I changed the name of the folder to minimod_tools, I should be changing all the files under that too?
For example: minimod_tools/minimod.md 
Screen Shot 2021-06-09 at 1 04 45 PM

**Comment by amichuda** [comment]
Yes! Perfect!

**Comment by britsanto** [comment]
Alright, I have just changed that. Hope that'll fix it, thanks for your patience!

**Pull request merged**
