### PR TITLE
[PR]: Tools fix

### PR DESCRIPTION
**Pull request by britsanto**
- Changed minimod.md folder name to minimod_tool.md
- Made file named minimod.md under the minimod_tool.md folder
- Not tool-related: fixed dimensions for new contact image in directory

### CODE REVIEW

**Review by amichuda — CHANGES_REQUESTED** [review]
this change from minimod.md -> minimod_tool.md doesn't fix the problem. The issue is that the folder has an extension, `.md`. This extension should only be for markdown files. You can name the folder `minimod` if you'd like.

**Comment by amichuda** [comment]
Perfect. Do those paths correspond to the paths in `mkdocs.yml`?

**Comment by britsanto** [comment]
I believe so

**Review by amichuda — APPROVED** [review]
> I believe so

Perfect

**Pull request merged**
