### PR TITLE
[PR]: Updated overview

### PR DESCRIPTION
**Pull request by britsanto**
- Updated the 'Key Messages' from Overview

### CODE REVIEW

**Review by amichuda — COMMENTED** [review]
@britsanto Can you take a look at this please? Otherwise I don't think the website will compile.

**Comment by britsanto** [comment]
Hmm, I only changed the content of the 'Key Messages' which I assumed doesn't require me to change anything in mkdocs.yml. Since you did say that this pull request contained changes from the previous pull requests, can I just discard this one and make a new one?

**Comment by amichuda** [comment]
This pull request shows that you also "changed tools format" where you changed the folder names. Those folder names have to show up in `mkdocs.yml`. if it would make it easier for you, we can discard this and make a new pull request, but the only thing that needs to be changed for this one to work is changing the folder names in the yaml file. Does that make sense?

**Comment by britsanto** [comment]
Oh,  I see what you mean. I think it would be easier for me to make a new pull request to avoid creating other mistakes. Thank you!

**Comment by amichuda** [comment]
Okay sounds good. I'm gonna close this then.

**Pull request closed without merging**
